### ISSUE TITLE
[Feature requests] Add bhagwad gita.

### ISSUE THREAD

**Issue by kcubeterm** [DevsExpo/FridayUserbot#296]
I saw we have bible options and that's works great but would be more awesome if it have .gita options which prints bhagwad gita texts.

**Comment by kcubeterm** [comment]
Here's the api https://bhagavadgita.io/api/

**Comment by StarkGang** [comment]
I am assigning this to myself, your request will be done within 2 days, Thanks For suggestion. Got Any Other Idea?

**Comment by kcubeterm** [comment]
@StarkGang you can get json file here 
https://github.com/kcubeterm/gita
