### ISSUE TITLE
[FEATURE-REQUEST] - Auto Approving for PM outgoing messages

### ISSUE THREAD

**Issue by pushpaksil69** [DevsExpo/FridayUserbot#305]
## Checklist
- [x] I Confirm this is awesome and would benefit the Software.
- [x] I Confirm That This is Not A Duplicate Feature Request

## Description
A detailed description of the Feature.
AUTO Approving for PM outgoing messqages like it was there in old version of friday (V7).

This is more of a bug because if two people with same/different userbots try to chat in dms, then both userbots start giving warning until they block each other eventually. And this is highly annoying and irritating. So I would request whenever an user msgs first, the other person would get auto-approved and the bot wont keep spamming warnings for the other user. 

Thanks in advance :)
From @pushpak_op

**Comment by EverythingSuckz** [comment]
Sure, we'll be working on it.
