### ISSUE TITLE
[BUG] WHILE USING ```.fadd all``` COMMAND

### ISSUE THREAD

**Issue by pushpaksil69** [DevsExpo/FridayUserbot#308]
## Checklist
- [x] I Am Using Latest Version.
- [x] I have searched Issues And Pull Requests And I Confirm That This is Not A Duplicate Issue.

## Command Which Causes This Issue.
```.fadd all```

## Description
.fadd <fed id> works fine but whenever ```.fadd all``` is used, the bot returns this msg, (pic attached below)
Either My Logic Broke Or You Are Not Admin in Any Fed!

![image](https://user-images.githubusercontent.com/75492129/113437569-5eeff280-93d6-11eb-84b1-0ec5a03eda68.png)
 

## Traceback
No traceback in log group!

**Comment by StarkGang** [comment]
You are not admin in any fed 🤔🙄

**Comment by pushpaksil69** [comment]
Bro, I was the owner.... When I used ```.fadd <fed id>``` it worked fine

**Comment by pushpaksil69** [comment]
here is another pic, 
![Screenshot (35)](https://user-images.githubusercontent.com/75492129/113469829-3f8daf80-9440-11eb-81a7-a9ae0f435c9f.png)

**Comment by StarkGang** [comment]
For owner based fbans please add manually, friday will only extract fed admins fed-id, as people need that only. i am afraid i need to close this. 
Thank you
