### ISSUE TITLE
.fban bug,  .fadd bug 

### ISSUE THREAD

**Issue by deadkiller12** [DevsExpo/FridayUserbot#309]
!ERROR - REPORT!

Trace Back : Traceback (most recent call last):
  File "/main_startup/core/decorators.py", line 71, in wrapper
    await func(client, message)
  File "/xtraplugins/fban.py", line 103, in fban_s
    fed_s = await get_all_feds()
  File "/xtraplugins/dB/fban_db.py", line 19, in get_all_feds
    lol = [wow async for wow in fed.find()]
TypeError: 'async for' requires an object with __aiter__ method, got Cursor

Plugin-Name : xtraplugins.fban
Function Name : fban_s 
Date : 2021-04-03 
Time : 08:07:34

You can Forward This to @FridayChat, If You Think This is Serious A Error!

**Comment by StarkGang** [comment]
This is Issue. Has been fixed ig. if you encounter this error again, please open a bug report again.
Thanks You.
