### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rawana07** [DevsExpo/FridayUserbot#310]
## Checklist
- [x] I Am Using Latest Version.
- [x] I have searched Issues And Pull Requests And I Confirm That This is Not A Duplicate Issue.

## Command Which Causes This Issue.
Command Name, Filename, And Function name.
Afk

## Description
A detailed description of the Bug.
I logged afk but anyone texting me not getting afk warning ?!

## Traceback
TraceBack Of Bug (if any)

**Comment by StarkGang** [comment]
Fixed.

**Comment by Rawana07** [comment]
Not working yet...

**Comment by Rawana07** [comment]
> Fixed.

Not working bro
