### ISSUE TITLE
[FEATURE-REQUEST] PmPermit enable & disable system from heroku.

### ISSUE THREAD

**Issue by adnansidd99** [DevsExpo/FridayUserbot#311]
## Checklist
- [x] I Confirm this is awesome and would benefit the Software.
- [x] I Confirm That This is Not A Duplicate Feature Request

## Description
A detailed description of the Feature.

**Comment by StarkGang** [comment]
Done. Just ADD `PM_PSW` Var And Set To False. Thats it! 
Thank You.
