### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rawana07** [DevsExpo/FridayUserbot#318]
## Checklist
- [x] I Am Using Latest Version.
- [x] I have searched Issues And Pull Requests And I Confirm That This is Not A Duplicate Issue.

## Command Which Causes This Issue.
Command Name, Filename, And Function name.
Shift.py

## Description
A detailed description of the Bug.
I tried to forward all msgs from 1 chat to another

## Traceback
TraceBack Of Bug (if any)
!ERROR - REPORT!

Trace Back : Traceback (most recent call last):
  File "/plugins/shift.py", line 31, in shift
    fromchat =int(fromchat)
UnboundLocalError: local variable 'fromchat' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/main_startup/core/decorators.py", line 91, in wrapper
    await func(client, message)
  File "/plugins/shift.py", line 33, in shift
    if not (fromchat.startswith("@")):
UnboundLocalError: local variable 'fromchat' referenced before assignment

Plugin-Name : plugins.shift
Function Name : shift 
Date : 2021-05-15 
Time : 16:45:23

You can Forward This to @FridayChat, If You Think This is Serious A Error!

**Comment by StarkGang** [comment]
There is No Shift plugins :/

**Comment by StarkGang** [comment]
Invalid Issue / Closed On 24/05/21
