### ISSUE TITLE
Bot crashed[BUG]

### ISSUE THREAD

**Issue by Rawana07** [DevsExpo/FridayUserbot#322]
Bot crashing

## Checklist
- [x] I Am Using Latest Version.
- [x] I have searched Issues And Pull Requests And I Confirm That This is Not A Duplicate Issue.

## Command Which Causes This Issue.
Command Name, Filename, And Function name.

## Description
A detailed description of the Bug.

## Traceback
TraceBack Of Bug (if any)
pyrogram.errors.exceptions.not_acceptable_406.AuthKeyDuplicated: [406 AUTH_KEY_DUPLICATED]: The same authorization key (session file) was used in more than one place simultaneously. You must delete your session file and log in again with your phone number or bot token (caused by "InvokeWithLayer")

**Comment by Rawana07** [comment]
I tried changing repo too but it didn't worked

**Comment by InukaAsith** [comment]
@Rawana07 
Have you used same string session in two apps.
I also accidently faced this when I used sape api id and hash for two pyrogram apps

**Comment by Rawana07** [comment]
No. . I'm using Friday only..

**Comment by StarkGang** [comment]
This is Not Related To Friday. please report to @delivrance
